name: griffin script developer guide
titile: Griffin Script Developer Guide
url: griffinscript.github.io
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
markdown: kramdown
