name: griffin script developer guide
url: griffinscript.github.io
theme: jekyll-theme-architect
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
markdown: kramdown
