name: griffin script developer guide
url: griffinscript.github.io
remote_theme: kitian616/jekyll-TeXt-theme
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
markdown: kramdown
